Build lxml and xmlsec from source instead of installing binaries
since it causes a mismatch in versions
xmlsec.InternalError: (-1, 'lxml & xmlsec libxml2 library version mismatch')